port: 3000
https: true
proxy:
  /gewinnspiele:
    target: http://localhost:9000
    secure: false
    changeOrigin: true
    logLevel: debug
  /vsk:
    target: http://localhost:9000
    secure: false
    changeOrigin: true
    logLevel: debug
  /:
    target: https://webint.oeamtc.at
    secure: false
    changeOrigin: true
    logLevel: debug
